# TODO:
# Interesting issue here - we can't sync the repo revs from a requirements.txt due to
# caching issues -
# https://github.com/pre-commit/pre-commit/issues/730
#
# Seems like this means we also can't read from a poetry lock file. Might need to create
# our own solution for keeping these in sync.
# This might be a good place to start -
# https://pre-commit.com/#repository-local-hooks
default_stages: [commit]

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        additional_dependencies: ["toml"]
        args: ["-c", "pyproject.toml"]
  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.2"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
  # mypy is running locally because there's no way to lock down the pre-commit mirror of
  # mypy to a tag that aligns to the mypy version. The mirror repo has it's own versioning
  # strategy
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./scripts/run-mypy.sh"
        language: python
        additional_dependencies: ["mypy==0.982"]
        types: [python]
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
